import { hashSync } from "bcryptjs";
import { Pool, type PoolClient, type QueryResult, type QueryResultRow } from "pg";

import type { PingFeature } from "@/lib/types";
const DEFAULT_ADMIN_USERNAME = process.env.LORAWAN_ADMIN_USERNAME?.trim() || "admin";
const DEFAULT_ADMIN_PASSWORD = process.env.LORAWAN_ADMIN_PASSWORD?.trim() || "admin1234";

type LegacyPingRecord = {
  board_id: string;
  counter: number;
  gateway_name: string | null;
  rssi: number;
  snr: number | null;
  observed_at: string;
  longitude: number;
  latitude: number;
  rssi_stabilized: number | null;
  rssi_bonus: number | null;
  network: string | null;
};

declare global {
  var __lorawanPgPool: Pool | undefined;
  var __lorawanDbReadyPromise: Promise<void> | undefined;
}

function getDatabaseUrl(): string {
  const databaseUrl = process.env.DATABASE_URL?.trim();

  if (!databaseUrl) {
    throw new Error("DATABASE_URL must be set to use PostgreSQL.");
  }

  return databaseUrl;
}

function getPoolInstance(): Pool {
  if (!globalThis.__lorawanPgPool) {
    globalThis.__lorawanPgPool = new Pool({ connectionString: getDatabaseUrl() });
  }

  return globalThis.__lorawanPgPool;
}

async function createTables(client: Pool | PoolClient): Promise<void> {
  await client.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT NOT NULL,
      password_hash TEXT NOT NULL DEFAULT '',
      role TEXT NOT NULL CHECK (role IN ('admin', 'user')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      auth_type TEXT NOT NULL CHECK (auth_type IN ('local', 'oauth')) DEFAULT 'local',
      oauth_provider TEXT,
      oauth_subject TEXT,
      CHECK (
        (auth_type = 'local' AND oauth_provider IS NULL AND oauth_subject IS NULL) OR
        (auth_type = 'oauth' AND oauth_provider IS NOT NULL AND oauth_subject IS NOT NULL)
      )
    );

    CREATE TABLE IF NOT EXISTS user_boards (
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      board_id TEXT NOT NULL,
      PRIMARY KEY (user_id, board_id)
    );

    CREATE TABLE IF NOT EXISTS sessions (
      id TEXT PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      expires_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS ping_features (
      feature_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      board_id TEXT NOT NULL,
      counter INTEGER NOT NULL,
      gateway_name TEXT,
      rssi INTEGER NOT NULL,
      snr DOUBLE PRECISION,
      observed_at TIMESTAMPTZ NOT NULL,
      longitude DOUBLE PRECISION NOT NULL,
      latitude DOUBLE PRECISION NOT NULL,
      rssi_stabilized INTEGER,
      rssi_bonus INTEGER,
      network TEXT
    );

    CREATE UNIQUE INDEX IF NOT EXISTS idx_users_local_username
      ON users (username)
      WHERE auth_type = 'local';

    CREATE UNIQUE INDEX IF NOT EXISTS idx_users_oauth_identity
      ON users (oauth_provider, oauth_subject)
      WHERE auth_type = 'oauth';

    CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions (expires_at);
    CREATE INDEX IF NOT EXISTS idx_user_boards_user_id ON user_boards (user_id);
    CREATE INDEX IF NOT EXISTS idx_ping_features_observed_at ON ping_features (observed_at);
    CREATE INDEX IF NOT EXISTS idx_ping_features_board_counter ON ping_features (board_id, counter);
  `);
}

async function insertPingRecords(client: Pool | PoolClient, records: LegacyPingRecord[]): Promise<void> {
  if (records.length === 0) {
    return;
  }

  const chunkSize = 1_000;

  for (let index = 0; index < records.length; index += chunkSize) {
    const chunk = records.slice(index, index + chunkSize);
    await client.query(
      `
        INSERT INTO ping_features (
          board_id,
          counter,
          gateway_name,
          rssi,
          snr,
          observed_at,
          longitude,
          latitude,
          rssi_stabilized,
          rssi_bonus,
          network
        )
        SELECT
          entry.board_id,
          entry.counter,
          entry.gateway_name,
          entry.rssi,
          entry.snr,
          entry.observed_at::timestamptz,
          entry.longitude,
          entry.latitude,
          entry.rssi_stabilized,
          entry.rssi_bonus,
          entry.network
        FROM jsonb_to_recordset($1::jsonb) AS entry(
          board_id text,
          counter integer,
          gateway_name text,
          rssi integer,
          snr double precision,
          observed_at text,
          longitude double precision,
          latitude double precision,
          rssi_stabilized integer,
          rssi_bonus integer,
          network text
        )
      `,
      [JSON.stringify(chunk)],
    );
  }
}

function toLegacyPingRecord(feature: PingFeature): LegacyPingRecord {
  return {
    board_id: String(feature.properties.boardID),
    counter: Number(feature.properties.counter),
    gateway_name: feature.properties.gateway ?? null,
    rssi: Number(feature.properties.rssi),
    snr: feature.properties.snr == null ? null : Number(feature.properties.snr),
    observed_at: feature.properties.time,
    longitude: Number(feature.geometry.coordinates[0]),
    latitude: Number(feature.geometry.coordinates[1]),
    rssi_stabilized: feature.properties.rssi_stabilized == null ? null : Number(feature.properties.rssi_stabilized),
    rssi_bonus: feature.properties.rssi_bonus == null ? null : Number(feature.properties.rssi_bonus),
    network: feature.properties.network === "chirpstack" ? "chirpstack" : null,
  };
}

async function seedDefaultAdmin(client: PoolClient): Promise<void> {
  const { rows } = await client.query<{ count: string }>("SELECT COUNT(*)::text AS count FROM users WHERE role = 'admin'");

  if (Number(rows[0]?.count ?? 0) > 0) {
    return;
  }

  await client.query(
    "INSERT INTO users (username, password_hash, role, auth_type) VALUES ($1, $2, 'admin', 'local')",
    [DEFAULT_ADMIN_USERNAME, hashSync(DEFAULT_ADMIN_PASSWORD, 12)],
  );
}

async function initializeDatabase(): Promise<void> {
  const pool = getPoolInstance();
  const client = await pool.connect();

  try {
    await client.query("BEGIN");
    await createTables(client);
    await seedDefaultAdmin(client);
    await client.query("COMMIT");
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

export async function ensureDatabaseReady(): Promise<void> {
  if (!globalThis.__lorawanDbReadyPromise) {
    globalThis.__lorawanDbReadyPromise = initializeDatabase();
  }

  await globalThis.__lorawanDbReadyPromise;
}

export async function query<T extends QueryResultRow = QueryResultRow>(
  text: string,
  values?: unknown[],
): Promise<QueryResult<T>> {
  await ensureDatabaseReady();
  return getPoolInstance().query<T>(text, values);
}

export async function withTransaction<T>(callback: (client: PoolClient) => Promise<T>): Promise<T> {
  await ensureDatabaseReady();
  const client = await getPoolInstance().connect();

  try {
    await client.query("BEGIN");
    const result = await callback(client);
    await client.query("COMMIT");
    return result;
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

export async function queryPingTimes(
  boardID: string,
  counters: number[],
  network: "ttn" | "chirpstack",
): Promise<Map<number, number>> {
  if (counters.length === 0) return new Map();
  const { rows } = await query<{ counter: string; observed_at: Date }>(
    `SELECT counter, observed_at FROM ping_features WHERE board_id = $1 AND counter = ANY($2) AND network = $3`,
    [boardID, counters, network],
  );
  const map = new Map<number, number>();
  for (const row of rows) {
    map.set(Number(row.counter), row.observed_at instanceof Date ? row.observed_at.getTime() : Date.parse(String(row.observed_at)));
  }
  return map;
}

export async function replacePingFeatures(features: PingFeature[]): Promise<void> {
  await withTransaction(async (client) => {
    await client.query("TRUNCATE TABLE ping_features RESTART IDENTITY");
    await insertPingRecords(client, features.map(toLegacyPingRecord));
  });
}