CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL CHECK (role IN ('admin', 'user')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  auth_type TEXT NOT NULL CHECK (auth_type IN ('local', 'oauth')) DEFAULT 'local',
  oauth_provider TEXT,
  oauth_subject TEXT,
  CHECK (
    (auth_type = 'local' AND oauth_provider IS NULL AND oauth_subject IS NULL) OR
    (auth_type = 'oauth' AND oauth_provider IS NOT NULL AND oauth_subject IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS user_boards (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  board_id TEXT NOT NULL,
  PRIMARY KEY (user_id, board_id)
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ping_features (
  feature_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_id TEXT NOT NULL,
  counter INTEGER NOT NULL,
  gateway_name TEXT,
  rssi INTEGER NOT NULL,
  snr DOUBLE PRECISION,
  observed_at TIMESTAMPTZ NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  rssi_stabilized INTEGER,
  rssi_bonus INTEGER,
  network TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_local_username
  ON users (username)
  WHERE auth_type = 'local';

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_oauth_identity
  ON users (oauth_provider, oauth_subject)
  WHERE auth_type = 'oauth';

CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions (expires_at);
CREATE INDEX IF NOT EXISTS idx_user_boards_user_id ON user_boards (user_id);
CREATE INDEX IF NOT EXISTS idx_ping_features_observed_at ON ping_features (observed_at);
CREATE INDEX IF NOT EXISTS idx_ping_features_board_counter ON ping_features (board_id, counter);